workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      java: 21        # <-- tambah spasi setelah titik dua
      vars:
        NODE_VERSION: "20"

    scripts:
      - name: Install dependencies
        script: npm ci --prefer-offline

      - name: Build Web (Vite)
        script: npm run build

      - name: Sync Capacitor Android
        script: npx cap sync android

      - name: Fix gradlew permission
        working_directory: android
        script: chmod +x gradlew

      - name: Build APK Release
        working_directory: android
        script: ./gradlew assembleRelease --stacktrace

    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk